<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHEGQg0N\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHEGQg0N/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHEGQg0N.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHEGQg0N\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHEGQg0N\App_KernelDevDebugContainer([
    'container.build_hash' => 'HEGQg0N',
    'container.build_id' => 'f5423b85',
    'container.build_time' => 1648346388,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHEGQg0N');
