<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSrHOf92\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSrHOf92/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSrHOf92.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSrHOf92\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSrHOf92\App_KernelDevDebugContainer([
    'container.build_hash' => 'SrHOf92',
    'container.build_id' => '01c94161',
    'container.build_time' => 1648344099,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSrHOf92');
