<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB9J5Kp3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB9J5Kp3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB9J5Kp3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB9J5Kp3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB9J5Kp3\App_KernelDevDebugContainer([
    'container.build_hash' => 'B9J5Kp3',
    'container.build_id' => '5ada267b',
    'container.build_time' => 1648414521,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB9J5Kp3');
