<?php

namespace Container9ICJmnm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getByAgeControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ByAgeController' shared autowired service.
     *
     * @return \App\Controller\ByAgeController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ByAgeController.php';

        $container->services['App\\Controller\\ByAgeController'] = $instance = new \App\Controller\ByAgeController(($container->privates['App\\Repository\\AgeRepository'] ?? $container->load('getAgeRepositoryService')), ($container->privates['App\\Repository\\ItemRepository'] ?? $container->load('getItemRepositoryService')), ($container->privates['App\\Repository\\CategoryRepository'] ?? $container->load('getCategoryRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.l1ae.Qz'] ?? $container->load('get_ServiceLocator_L1ae_QzService'))->withContext('App\\Controller\\ByAgeController', $container));

        return $instance;
    }
}
